apiVersion: apps/v1                  # Using the apps/v1 API for Deployment
kind: Deployment                     # The resource type is Deployment
metadata:
  name: myapp                        # Name of the deployment
  namespace: myapp
spec:
  replicas: 2                        # Run 2 pods of the application
  selector:
    matchLabels:
      app: myapp                     # Select pods with label app=myapp
  template:                          # Pod template section
    metadata:
      labels:
        app: myapp                   # Label the pods with app=myapp
    spec:
      containers:
      - name: myapp                  # Name of the container
        image: kai554/test:v4
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

